stages:
  - test
  - build

frontend-test:
  image: node:latest
  stage: test
  before_script:
    - cd frontend
    - npm install
  script:
    - npm run test
  artifacts:
    paths:
      - coverage/
    when: always
    reports:
      junit:
        - junit.xml

backend-test:
  image: node:latest
  stage: test
  before_script:
    - cd backend
    - npm install
  script:
    - npm run test:ci
  artifacts:
    paths:
      - coverage/
    when: always
    reports:
      junit:
        - junit.xml

frontend-build:
  image: node:latest
  stage: build
  before_script:
    - cd frontend
    - npm install
  script:
    - npm run dev

backend-build:
  image: node:latest
  stage: build
  before_script:
    - cd backend
    - npm install
  script:
    - npm run start
